config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    resources :slots
  end

  root to: 'cars#login'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :slots, dependent: :destroy

  validates :name, presence: true
  validates :category, inclusion: {in: %w(A B C), message: "can only be of type A, B or C"}
  validates :description, presence: true
end

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :car

  validates :startdate, presence: true
  validates :enddate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: :login

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params.require(:car).permit(:name, :category, :description))
    if @car.save
      redirect_to @car
    else
      render 'new'
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def index
    @cars = Car.all
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @slot = @car.slots.new(params[:slot].permit(:startdate, :enddate))

    # we need to check if booking is valid, it means:
    #  if end date of the booking is not lower than start date
    #  if booking does not interlace with some other bookings
    if @slot.startdate <= @slot.enddate
      @canBeSaved = true

      numberOfSlots = @car.slots.count-1
      @canBeSaved = 0.upto(numberOfSlots) do |i|
        if @slot.startdate >= @car.slots[i].startdate and @slot.startdate <= @car.slots[i].enddate
          break false
        elsif @slot.enddate >= @car.slots[i].startdate and @slot.enddate <= @car.slots[i].enddate
          break false
        elsif @slot.startdate <= @car.slots[i].startdate and @slot.enddate >= @car.slots[i].enddate
          break false
        end
      end
      @slot.save if @canBeSaved
    end
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:car_id])
    @slot = @car.slots.find(params[:id])
    @slot.destroy
    redirect_to car_path(@car)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/cars/index.html.erb
<div class="body">
  <div class = "menu">
    <%= link_to "Dodaj samochód do bazy", new_car_path, style: 'text-decoration: none; color: white' %>
  </div>

  <h2>Samochody w bazie</h2>

  <table>
    <tr>
      <th style = "width: 10%">Nazwa</th>
      <th style = "width: 5%">Klasa</th>
      <th style = "width: 70%">Opis</th>
      <th></th>
    </tr>
    <% @cars.each do |car| %>
        <tr>
          <td><%= link_to car.name, car, style: 'color: black' %></td>
          <td><%= car.category %></td>
          <td><%= car.description %></td>
          <td><%= link_to "Usuń samochód", car_path(car), method: :delete, data: {confirm: "Czy na pewno usunąć ten samochód z bazy?"},
                          style: 'text-decoration: none; color: red' %></td>
        </tr>
    <% end %>
  </table>

  <% if @cars.size == 0 %>
      <p>--Brak samochodów w bazie--</p>
  <% end %>
</div>

app/views/cars/login.html.erb
<div id = "logging">
  <img id = "car_img" src="assets/car.png">
  <%= link_to "Zaloguj się", cars_path, style: 'text-decoration: none; color: black' %>
</div>

app/views/cars/new.html.erb
<div class="body">
  <div class = "menu">
    <%= link_to "Lista samochodów", cars_path, style: 'text-decoration: none; color: white'  %>
  </div>

  <% if @car.errors.any? %>
      <div class = "error">
        <h3><%= pluralize(@car.errors.count, "error") %> prohibited this car from being added:</h3>
        <ul>
          <% @car.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <h2>Nowy samochód</h2>

  <%= form_for :car, url: cars_path do |f| %>
      <p>
        <%= f.label "Nazwa samochodu: " %>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label "Klasa (kategoria): " %>
        <%= f.text_field :category %>
      </p>

      <p>
        <%= f.label "Opis: " %><br>
        <%= f.text_area :description %>
      </p>

      <p><%= f.submit "Dodaj ten samochód do bazy" %></p>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="body">
  <div class = "menu">
    <%= link_to "Lista samochodów", cars_path, style: 'text-decoration: none; color: white'  %>
  </div>

  <h2><%= @car.name + " (klasa " + @car.category + ")" %></h2>

  <p><%= @car.description %></p>

  <h4>Terminy, w których samochód jest wypożyczony:</h4>

  <table>
    <tr>
      <th style = "width: 30%">Początek wynajmu</th>
      <th style = "width: 30%">Koniec wynajmu</th>
      <th style = "width: 30%">Cena [PLN]</th>
      <th></th>
    </tr>
    <% @car.slots.each do |slot| %>
        <tr>
          <td><%= slot.startdate %> </td>
          <td><%= slot.enddate %> </td>
          <td><%= (slot.enddate - slot.startdate + 1).to_i * (@car.category == "A" ? 100 : (@car.category == "B" ? 75 : 50)) %></td>
          <td><%= link_to "Usuń rezerwację", [slot.car, slot], method: :delete, data: {confirm: "Czy na pewno usunąć tę rezerwację?"},
                          style: 'text-decoration: none; color: red'%> </td>
        </tr>
    <% end %>
  </table>

  <% if @car.slots.size == 0 %>
    <p>--Brak rezerwacji--</p>
  <% end %>

  <h4>Wypożycz samochód</h4>

    <%= form_for([@car,@car.slots.build]) do |f| %>
        <p>
          <%= f.label "Początek wypożyczenia: " %>
          <%= f.date_select :startdate %>
        </p>

        <p>
          <%= f.label "Koniec wypożyczenia: " %>
          <%= f.date_select :enddate %>
        </p>

        <p><%= f.submit "Zarezerwuj"%></p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="utf-8" />
  <title>Wypożyczalnia samochodów</title>
  <meta name="keywords" content="samochód, wypożyczalnia" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <h1>Wypożyczalnia samochodów</h1>
</div>

<%= yield %>

<div class = "foot">
  <p id = "signum">Marcin Szot</p>
</div>

</body>